export class reporteDireccionAcumulado{
    constructor(
        public ID: number,
        public PROGRAMADO: number,
        public EJECUCION: number,
        public POR_EJECUTAR: number,
        public PE: number,
        public ENERO_P: number,
        public ENERO_E: number,
        public FEBRERO_P: number,
        public FEBRERO_E: number,
        public MARZO_p: number,
        public MARZO_E: number,
        public ABRIL_P: number,
        public ABRIL_E: number,
        public MAYO_P: number,
        public MAYO_E: number,
        public JUNIO_P: number,
        public JUNIO_E: number,
        public JULIO_P: number,
        public JULIO_E: number,
        public AGOSTO_P: number,
        public AGOSTO_E: number,
        public SEPTIEMBRE_P: number,
        public SEPTIEMBRE_E: number,
        public OCTUBRE_P: number,
        public OCTUBRE_E: number,
        public NOVIEMBRE_P: number,
        public NOVIEMBRE_E: number,
        public DICIEMBRE_P: number,
        public DICIEMBRE_E: number
    ){}
}